[package]
name = "ayarify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
ego-tree = "0.6.2"
html5ever = "0.26"
scraper = "0.19.0"

[dev-dependencies]
regex = "1.10.4"
rstest = "0.21.0"
